// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarPark.proto

package org.sample.park.autogenerated;

public interface ParkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.park.ParkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.sample.park.Vehicle vehicle = 1;</code>
   */
  boolean hasVehicle();
  /**
   * <code>.org.sample.park.Vehicle vehicle = 1;</code>
   */
  org.sample.park.autogenerated.Vehicle getVehicle();
  /**
   * <code>.org.sample.park.Vehicle vehicle = 1;</code>
   */
  org.sample.park.autogenerated.VehicleOrBuilder getVehicleOrBuilder();
}
