// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarPark.proto

package org.sample.park.autogenerated;

/**
 * Protobuf type {@code org.sample.park.autogenerated.ParkRequest}
 */
public  final class ParkRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.sample.park.autogenerated.ParkRequest)
    ParkRequestOrBuilder {
  // Use ParkRequest.newBuilder() to construct.
  private ParkRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParkRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ParkRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.sample.park.autogenerated.Vehicle.Builder subBuilder = null;
            if (vehicle_ != null) {
              subBuilder = vehicle_.toBuilder();
            }
            vehicle_ = input.readMessage(org.sample.park.autogenerated.Vehicle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vehicle_);
              vehicle_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.sample.park.autogenerated.CarPark.internal_static_org_sample_park_ParkRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.sample.park.autogenerated.CarPark.internal_static_org_sample_park_ParkRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.sample.park.autogenerated.ParkRequest.class, org.sample.park.autogenerated.ParkRequest.Builder.class);
  }

  public static final int VEHICLE_FIELD_NUMBER = 1;
  private org.sample.park.autogenerated.Vehicle vehicle_;
  /**
   * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
   */
  public boolean hasVehicle() {
    return vehicle_ != null;
  }
  /**
   * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
   */
  public org.sample.park.autogenerated.Vehicle getVehicle() {
    return vehicle_ == null ? org.sample.park.autogenerated.Vehicle.getDefaultInstance() : vehicle_;
  }
  /**
   * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
   */
  public org.sample.park.autogenerated.VehicleOrBuilder getVehicleOrBuilder() {
    return getVehicle();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (vehicle_ != null) {
      output.writeMessage(1, getVehicle());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (vehicle_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVehicle());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.sample.park.autogenerated.ParkRequest)) {
      return super.equals(obj);
    }
    org.sample.park.autogenerated.ParkRequest other = (org.sample.park.autogenerated.ParkRequest) obj;

    boolean result = true;
    result = result && (hasVehicle() == other.hasVehicle());
    if (hasVehicle()) {
      result = result && getVehicle()
          .equals(other.getVehicle());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVehicle()) {
      hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
      hash = (53 * hash) + getVehicle().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sample.park.autogenerated.ParkRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.sample.park.autogenerated.ParkRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sample.park.autogenerated.ParkRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.sample.park.autogenerated.ParkRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.sample.park.autogenerated.ParkRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.sample.park.autogenerated.ParkRequest)
      org.sample.park.autogenerated.ParkRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sample.park.autogenerated.CarPark.internal_static_org_sample_park_ParkRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sample.park.autogenerated.CarPark.internal_static_org_sample_park_ParkRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sample.park.autogenerated.ParkRequest.class, org.sample.park.autogenerated.ParkRequest.Builder.class);
    }

    // Construct using org.sample.park.autogenerated.ParkRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
      } else {
        vehicle_ = null;
        vehicleBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.sample.park.autogenerated.CarPark.internal_static_org_sample_park_ParkRequest_descriptor;
    }

    public org.sample.park.autogenerated.ParkRequest getDefaultInstanceForType() {
      return org.sample.park.autogenerated.ParkRequest.getDefaultInstance();
    }

    public org.sample.park.autogenerated.ParkRequest build() {
      org.sample.park.autogenerated.ParkRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.sample.park.autogenerated.ParkRequest buildPartial() {
      org.sample.park.autogenerated.ParkRequest result = new org.sample.park.autogenerated.ParkRequest(this);
      if (vehicleBuilder_ == null) {
        result.vehicle_ = vehicle_;
      } else {
        result.vehicle_ = vehicleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.sample.park.autogenerated.ParkRequest) {
        return mergeFrom((org.sample.park.autogenerated.ParkRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.sample.park.autogenerated.ParkRequest other) {
      if (other == org.sample.park.autogenerated.ParkRequest.getDefaultInstance()) return this;
      if (other.hasVehicle()) {
        mergeVehicle(other.getVehicle());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.sample.park.autogenerated.ParkRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.sample.park.autogenerated.ParkRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.sample.park.autogenerated.Vehicle vehicle_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sample.park.autogenerated.Vehicle, org.sample.park.autogenerated.Vehicle.Builder, org.sample.park.autogenerated.VehicleOrBuilder> vehicleBuilder_;
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public boolean hasVehicle() {
      return vehicleBuilder_ != null || vehicle_ != null;
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public org.sample.park.autogenerated.Vehicle getVehicle() {
      if (vehicleBuilder_ == null) {
        return vehicle_ == null ? org.sample.park.autogenerated.Vehicle.getDefaultInstance() : vehicle_;
      } else {
        return vehicleBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public Builder setVehicle(org.sample.park.autogenerated.Vehicle value) {
      if (vehicleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vehicle_ = value;
        onChanged();
      } else {
        vehicleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public Builder setVehicle(
        org.sample.park.autogenerated.Vehicle.Builder builderForValue) {
      if (vehicleBuilder_ == null) {
        vehicle_ = builderForValue.build();
        onChanged();
      } else {
        vehicleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public Builder mergeVehicle(org.sample.park.autogenerated.Vehicle value) {
      if (vehicleBuilder_ == null) {
        if (vehicle_ != null) {
          vehicle_ =
            org.sample.park.autogenerated.Vehicle.newBuilder(vehicle_).mergeFrom(value).buildPartial();
        } else {
          vehicle_ = value;
        }
        onChanged();
      } else {
        vehicleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public Builder clearVehicle() {
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
        onChanged();
      } else {
        vehicle_ = null;
        vehicleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public org.sample.park.autogenerated.Vehicle.Builder getVehicleBuilder() {
      
      onChanged();
      return getVehicleFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    public org.sample.park.autogenerated.VehicleOrBuilder getVehicleOrBuilder() {
      if (vehicleBuilder_ != null) {
        return vehicleBuilder_.getMessageOrBuilder();
      } else {
        return vehicle_ == null ?
            org.sample.park.autogenerated.Vehicle.getDefaultInstance() : vehicle_;
      }
    }
    /**
     * <code>.org.sample.park.autogenerated.Vehicle vehicle = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sample.park.autogenerated.Vehicle, org.sample.park.autogenerated.Vehicle.Builder, org.sample.park.autogenerated.VehicleOrBuilder> 
        getVehicleFieldBuilder() {
      if (vehicleBuilder_ == null) {
        vehicleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sample.park.autogenerated.Vehicle, org.sample.park.autogenerated.Vehicle.Builder, org.sample.park.autogenerated.VehicleOrBuilder>(
                getVehicle(),
                getParentForChildren(),
                isClean());
        vehicle_ = null;
      }
      return vehicleBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.sample.park.autogenerated.ParkRequest)
  }

  // @@protoc_insertion_point(class_scope:org.sample.park.autogenerated.ParkRequest)
  private static final org.sample.park.autogenerated.ParkRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.sample.park.autogenerated.ParkRequest();
  }

  public static org.sample.park.autogenerated.ParkRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParkRequest>
      PARSER = new com.google.protobuf.AbstractParser<ParkRequest>() {
    public ParkRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParkRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParkRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParkRequest> getParserForType() {
    return PARSER;
  }

  public org.sample.park.autogenerated.ParkRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

